---
# -----------------------------
# This playbook transfer thekubeconfig file from the remote node to the local node.
# It creates a merged kubeconfig file in order to export the context of both local and remote clusters.
# Finally, it perform the in-band peering from the local node to the central cluster.
# -----------------------------

- name: Transfer kubeconfig from remote to local and prepare it
  hosts: 127.0.0.1
  gather_facts: no

  roles:
    - role: liqo-get-kubeconfig-remote

- name: Transfer modified kubeconfig to remote node
  hosts: 127.0.0.1

  roles:
    - role: liqo-push-kubeconfig-local
    - role: liqo-outgoing