---

- name: Install k3s without traefik
  shell: 'sudo curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -s - --write-kubeconfig-mode 644-' 

- name: Change ownership of k3s
  ansible.builtin.command: sudo chown mgmt /etc/rancher/k3s/k3s.yaml

- name: Change access to k3s
  ansible.builtin.command: sudo chmod 644 /etc/rancher/k3s/k3s.yaml

- name: Export KUBECONFIG in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml'
    regexp: '^export KUBECONFIG='
    state: present